services:
  webserver:
    build: 
      context: ./bin/${PHPVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
    networks:
      - my_custom_network
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"    
    volumes: 
      - ${DOCUMENT_ROOT-../}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    depends_on:
      - database
  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: '${COMPOSE_PROJECT_NAME}-database'
    networks:
      my_custom_network:
        ipv4_address: 172.25.0.10
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-/home/filipe/mysql-data-wordpress-curso}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    networks:
      - my_custom_network
    environment:
      PMA_HOST: database      
      UPLOAD_LIMIT: 900M
      MEMORY_LIMIT: 1000M
      MAX_EXECUTION_TIME: 1000
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}      
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
    depends_on:
      - database

  redis:
    container_name: '${COMPOSE_PROJECT_NAME}-redis'
    networks:
      - my_custom_network
    image: redis:latest
    ports:
      - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16